[bootstrap.packages]
"apt:zsh" = "latest"

[bootstrap.mise_shell_activate]
bashrc = true
zshrc = true

[tools]
actionlint = "latest"
claude = "latest"
ghalint = "latest"
github-cli = "latest"
java = "temurin-25"
ktlint = "latest"
node = "lts"
pnpm = "latest"
shellcheck = "latest"
tombi = "latest"
zizmor = "latest"
