name: actionlint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/**

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-slim
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2.2.0
