# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - &setup-java
        name: Set up Java
        uses: jdx/mise-action@v4.3.0
        with:
          install_args: java

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6.3.0

      - name: Build with Gradle
        run: ./gradlew build jacocoTestReport

      - name: Upload artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          path: build/reports/tests/

      - name: Publish test report
        if: always()
        uses: ctrf-io/github-test-reporter@v1.3.0
        with:
          report-path: build/test-results/test/TEST-*.xml
          title: Test Report
          use-suite-name: true
          integrations-config: |
            {
              "junit-to-ctrf": {
                "enabled": true
              }
            }

      - name: Upload coverage to Codecov
        if: github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v7.0.0
        with:
          fail_ci_if_error: true
          files: build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  dependency-submission:
    name: Dependency Submission
    runs-on: ubuntu-slim
    permissions:
      contents: write

    steps:
      - *checkout

      - *setup-java

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v6.3.0
