name: Validate Gradle Wrapper

on:
  - push
  - pull_request

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate checksum of Gradle Wrapper JAR file
        uses: gradle/actions/wrapper-validation@v3.3.0
